# ---- Load libraries ----
library(tibble)

# ---- Build data ----
# ONS geoportal query urls can be found on the "API Explorer" tab.
query_urls <-
  tribble(
    # Column Names
    ~data_set, ~type, ~notes, ~query_url, ~source,

    # Boundaries
    "countries", "boundaries", "Countries (December 2020) UK BUC", "https://opendata.arcgis.com/datasets/bb7104d3a9c04937be57e408288282dc_0.geojson", "https://geoportal.statistics.gov.uk/datasets/countries-december-2020-uk-buc/explore?location=54.650000%2C-3.250000%2C6.04",
    "ccg", "boundaries", "April 2020 - Ultra generalised", "https://ons-inspire.esriuk.com/arcgis/rest/services/Health_Boundaries/Clinical_Commissioning_Groups_April_2020_EN_BUC/MapServer/1/query?where=1%3D1&outFields=*&outSR=4326&f=json", "https://geoportal.statistics.gov.uk/datasets/clinical-commissioning-groups-april-2020-ultra-generalised-boundaries-en?geometry=-41.190%2C48.021%2C36.901%2C57.304",
    "counties_ua", "boundaries", "December 2019 - Ultra generalised", "https://ons-inspire.esriuk.com/arcgis/rest/services/Administrative_Boundaries/Counties_and_Unitary_Authorities_December_2019_Boundaries_UK_BUC2/MapServer/0/query?where=1%3D1&outFields=*&outSR=4326&f=json", "https://geoportal.statistics.gov.uk/datasets/counties-and-unitary-authorities-december-2019-boundaries-uk-buc?geometry=-39.482%2C47.293%2C38.609%2C56.716",
    "lad", "boundaries", "December 2019 - Ultra generalised", "https://opendata.arcgis.com/datasets/3a4fa2ce68f642e399b4de07643eeed3_0.geojson", "https://geoportal.statistics.gov.uk/datasets/ons::local-authority-districts-december-2019-boundaries-uk-buc/about",
    "lsoa", "boundaries", "Lower Layer Super Output Areas (December 2011) Boundaries Super Generalised Clipped (BSC) EW V3", "https://services1.arcgis.com/ESMARspQHYMw9BZ9/arcgis/rest/services/Lower_Layer_Super_Output_Areas_DEC_2011_EW_BSC_V3/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&f=json", "https://geoportal.statistics.gov.uk/datasets/lower-layer-super-output-areas-december-2011-boundaries-super-generalised-clipped-bsc-ew-v3?geometry=-25.519%2C50.522%2C21.173%2C55.161",
    "msoa", "boundaries", "December 2011 - Full resolution - clipped to the coastline (Mean High Water mark)", "https://services1.arcgis.com/ESMARspQHYMw9BZ9/arcgis/rest/services/Middle_Layer_Super_Output_Areas_December_2011_EW_BFC_V2/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&f=json", "https://geoportal.statistics.gov.uk/datasets/middle-layer-super-output-areas-december-2011-boundaries-full-clipped-bfc-ew-v3?geometry=-41.548%2C48.013%2C37.202%2C57.298",
    "stp", "boundaries", "April 2020 - Ultra generalised", "https://ons-inspire.esriuk.com/arcgis/rest/services/Health_Boundaries/Sustainability_and_Transformation_Partnerships_April_2020_Boundaries_EN_BUC/MapServer/0/query?where=1%3D1&outFields=*&outSR=4326&f=json", "https://geoportal.statistics.gov.uk/datasets/sustainability-and-transformation-partnerships-april-2020-boundaries-en-buc?geometry=-41.520%2C48.021%2C37.230%2C57.304",
    "towns_cities", "boundaries", "December 2015 - Generalised Grid (50m) - clipped to the coastline (Mean High Water mark)", "https://services1.arcgis.com/ESMARspQHYMw9BZ9/arcgis/rest/services/Major_Towns_and_Cities_December_2015_EW_BGG/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&f=json", "https://geoportal.statistics.gov.uk/datasets/major-towns-and-cities-december-2015-boundaries",
    "wards", "boundaries", "December 2020 - Super generalised (200m) - clipped to the coastline (Mean High Water mark)", "https://services1.arcgis.com/ESMARspQHYMw9BZ9/arcgis/rest/services/Wards_December_2020_UK_BSC_V2/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&f=json", "https://geoportal.statistics.gov.uk/datasets/wards-december-2020-uk-bsc-v2",
    "hb", "boundaries", "2019", "https://maps.gov.scot/ATOM/shapefiles/SG_NHS_HealthBoards_2019.zip", "https://spatialdata.gov.scot/geonetwork/srv/eng/catalog.search;jsessionid=2BA249588D00C49F254018A42F2C6958#/metadata/f12c3826-4b4b-40e6-bf4f-77b9ed01dc14",
    "dz", "boundaries", "Data Zone Boundaries 2011", "https://maps.gov.scot/ATOM/shapefiles/SG_DataZoneBdry_2011.zip", "https://spatialdata.gov.scot/geonetwork/srv/eng/catalog.search#/metadata/7d3e8709-98fa-4d71-867c-d5c8293823f2",
    "iz", "boundaries", "Intermediate Zone Boundaries 2011", "https://maps.gov.scot/ATOM/shapefiles/SG_IntermediateZoneBdry_2011.zip", "https://spatialdata.gov.scot/geonetwork/srv/eng/catalog.search#/metadata/389787c0-697d-4824-9ca9-9ce8cb79d6f5",
    "soa", "boundaries", "2001", "https://www.opendatani.gov.uk/dataset/678697e1-ae71-41f3-abba-0ef5f3f352c2/resource/80392e82-8bee-42de-a1e3-82d1cbaa983f/download/soa2001.json", "https://www.opendatani.gov.uk/dataset/nisra-open-data-boundaries-super-output-areas-2011/resource/80392e82-8bee-42de-a1e3-82d1cbaa983f",
    "pfa", "boundaries", "2020", "https://opendata.arcgis.com/datasets/2a1e3c23f1f24f15808275f52b8ae20d_0.geojson", "https://geoportal.statistics.gov.uk/datasets/ons::police-force-areas-december-2020-ew-buc/explore",
    "trusts_ni", "boundaries", "2018", "https://www.opendatani.gov.uk/dataset/0b04b46c-49af-45d5-b277-91b10937a01b/resource/7fa52dde-90b8-446e-bb79-4871d1028cb4/download/dohtrustboundary.zip", "https://www.opendatani.gov.uk/dataset/department-of-health-trust-boundaries/resource/7fa52dde-90b8-446e-bb79-4871d1028cb4",
    "lhb", "boundaries", "2019", "https://ons-inspire.esriuk.com/arcgis/rest/services/Health_Boundaries/Local_Health_Boards_April_2019_Boundaries_WA_BUC/MapServer/0/query?where=1%3D1&outFields=*&outSR=4326&f=json", "https://geoportal.statistics.gov.uk/datasets/local-health-boards-april-2019-boundaries-wa-buc/explore?location=52.400000%2C-4.000000%2C8.70",

    # Points
    "nhs_trusts", "points", "Addresses of NHS Trusts to geocode", "https://files.digital.nhs.uk/assets/ods/current/etr.zip", "https://digital.nhs.uk/services/organisation-data-service/data-downloads/other-nhs-organisations",

    # Lookups
    "lsoa_msoa", "lookup", "Output Area to LSOA to MSOA to Local Authority District (December 2017) Lookup with Area Classifications in Great Britain", "https://opendata.arcgis.com/datasets/fe6c55f0924b4734adf1cf7104a0173e_0.csv", "http://geoportal.statistics.gov.uk/datasets/fe6c55f0924b4734adf1cf7104a0173e_0",
    "lsoa_ward", "lookup", "Lower Layer Super Output Area (2011) to Ward (2019) Lookup in England and Wales", "https://opendata.arcgis.com/datasets/15299a7b8e6c498d94a08b687c75b73f_0.csv", "https://geoportal.statistics.gov.uk/datasets/lower-layer-super-output-area-2011-to-ward-2019-lookup-in-england-and-wales",
    "msoa_lad", "lookup", "Middle Layer Super Output Area (2011) to Ward to LAD (December 2019)", "https://services1.arcgis.com/ESMARspQHYMw9BZ9/arcgis/rest/services/MSOA11_WD19_LAD19_EW_LU/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&f=json", "https://geoportal.statistics.gov.uk/datasets/0b3c76d1eb5e4ffd98a3679ab8dea605_0/geoservice",
    "ccg_stp", "lookup", "Clinical Commissioning Group to STPs (April 2020) Lookup in England", "https://services1.arcgis.com/ESMARspQHYMw9BZ9/arcgis/rest/services/CCG20_STP20_EN_LU/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&f=json", "https://geoportal.statistics.gov.uk/datasets/clinical-commissioning-group-to-stps-april-2020-lookup-in-england/geoservice",
    "dz_iz_lad", "lookup", "Data zone to intermediate zone and local authority in Scotland", "https://www.gov.scot/binaries/content/documents/govscot/publications/statistics/2020/01/scottish-index-of-multiple-deprivation-2020-data-zone-look-up-file/documents/scottish-index-of-multiple-deprivation-data-zone-look-up/scottish-index-of-multiple-deprivation-data-zone-look-up/govscot%3Adocument/SIMD_2020_Datazone_lookup_tool.xlsx", "https://www.gov.scot/publications/scottish-index-of-multiple-deprivation-2020-data-zone-look-up/",
    "hb_lad", "lookup", "NHS Health Boundaries to Local Authority Districts in Scotland", "https://www.opendata.nhs.scot/km/datastore/dump/967937c4-8d67-4f39-974f-fd58c4acfda5?bom=True", "https://www.opendata.nhs.scot/km/dataset/geography-codes-and-labels/resource/967937c4-8d67-4f39-974f-fd58c4acfda5",
    "postcode_lad", "lookup", "A best-fit lookup between postcodes and LAD classifications as at August 2020 in the UK", "https://www.arcgis.com/sharing/rest/content/items/9f629cd0c2fb42beb0d79a474fee4776/data", "https://geoportal.statistics.gov.uk/datasets/9f629cd0c2fb42beb0d79a474fee4776/about",
    "sa_soa_lgd", "lookup", "Small Areas (2011) to SOAs to Local Government Districts (December 2018) Lookup with Area Classifications in Northern Ireland", "https://opendata.arcgis.com/datasets/096a7ccbc8e244cc972189b2f07a321a_0.csv", "https://geoportal.statistics.gov.uk/datasets/small-areas-2011-to-soas-to-local-government-districts-december-2018-lookup-with-area-classifications-in-northern-ireland",
    "lsoa_ccg_stp", "lookup", "LSOA (2011) to Clinical Commissioning Groups to Sustainability and Transformation Partnerships (April 2021) Lookup in England", "https://opendata.arcgis.com/datasets/c7e5f64bf2a7447c92db212f27093230_0.geojson", "https://geoportal.statistics.gov.uk/datasets/ons::lsoa-2011-to-clinical-commissioning-groups-to-sustainability-and-transformation-partnerships-april-2021-lookup-in-england/about",
    "trust_lad", "lookup", "Catchment population areas 2020", "https://app.box.com/index.php?rm=box_download_shared_file&shared_name=qh8gzpzeo1firv1ezfxx2e6c4tgtrudl&file_id=f_646039228900", "https://app.box.com/s/qh8gzpzeo1firv1ezfxx2e6c4tgtrudl",
    "counties_ua_lad", "lookup", "Lower Tier Local Authority to Upper Tier Local Authority (December 2019) Lookup in England and Wales", "https://services1.arcgis.com/ESMARspQHYMw9BZ9/arcgis/rest/services/LTLA19_UTLA19_EW_LUv1/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&f=json", "https://geoportal.statistics.gov.uk/datasets/lower-tier-local-authority-to-upper-tier-local-authority-december-2019-lookup-in-england-and-wales/explore?showTable=true",
    "lad_region", "lookup", "Local Authority District to Region (April 2019) Lookup in England", "https://opendata.arcgis.com/datasets/3ba3daf9278f47daba0f561889c3521a_0.geojson", "https://geoportal.statistics.gov.uk/datasets/ons::local-authority-district-to-region-april-2019-lookup-in-england/about",

    # Rural-Urban Classifications
    "ruc_england_wales", "ruc", "Rural-urban classifications in England and Wales", "https://opendata.arcgis.com/datasets/276d973d30134c339eaecfc3c49770b3_0.csv", "https://geoportal.statistics.gov.uk/datasets/rural-urban-classification-2011-of-lower-layer-super-output-areas-in-england-and-wales",
    "ruc_scotland", "ruc", "Rural-urban classifications in Scotland", "https://www.gov.scot/binaries/content/documents/govscot/publications/advice-and-guidance/2018/03/scottish-government-urban-rural-classification-2016/documents/scottish-government-urban-rural-classification-2016-data-zone-lookup/scottish-government-urban-rural-classification-2016-data-zone-lookup/govscot%3Adocument/00544928.csv", "https://www.gov.scot/publications/scottish-government-urban-rural-classification-2016/pages/2/",
    "ruc_ni", "ruc", "Rural-urban classifications in Northern Ireland", "https://www.nisra.gov.uk/sites/nisra.gov.uk/files/publications/Settlement15-lookup_0.xls", "https://www.nisra.gov.uk/support/geography/urban-rural-classification",

    # Population estimates
    "pop_lsoa", "population", "Lower layer Super Output Area population estimates: mid-2019", "https://www.ons.gov.uk/file?uri=%2fpeoplepopulationandcommunity%2fpopulationandmigration%2fpopulationestimates%2fdatasets%2flowersuperoutputareamidyearpopulationestimates%2fmid2019sape22dt2/sape22dt2mid2019lsoasyoaestimatesunformatted.zip", "https://www.ons.gov.uk/peoplepopulationandcommunity/populationandmigration/populationestimates/datasets/lowersuperoutputareamidyearpopulationestimates",
    "pop_msoa", "population", "Middle layer Super Output Area population estimates: mid-2019", "https://www.ons.gov.uk/file?uri=/peoplepopulationandcommunity/populationandmigration/populationestimates/datasets/middlesuperoutputareamidyearpopulationestimates/mid2019sape22dt4/sape22dt4mid2019msoasyoaestimatesunformatted.zip", "https://www.ons.gov.uk/peoplepopulationandcommunity/populationandmigration/populationestimates/datasets/middlesuperoutputareamidyearpopulationestimates",
    "pop_dz", "population", "Scotland Data Zone population estimates: mid-2019", "https://www.opendata.nhs.scot/datastore/dump/c505f490-c201-44bd-abd1-1bd7a64285ee?bom=True", "https://www.opendata.nhs.scot/dataset/population-estimates/resource/c505f490-c201-44bd-abd1-1bd7a64285ee",
    "pop_iz", "population", "Scotland Intermediate Zone population estimates: mid-2019", "https://www.opendata.nhs.scot/dataset/7f010430-6ce1-4813-b25c-f7f335bdc4dc/resource/93df4c88-f74b-4630-abd8-459a19b12f47/download/iz2011-pop-est_02042020.csv", "https://www.opendata.nhs.scot/dataset/population-estimates/resource/93df4c88-f74b-4630-abd8-459a19b12f47",
    "pop_soa", "population", "Northern Ireland Super Output Area population estimates: mid-2019", "https://www.nisra.gov.uk/sites/nisra.gov.uk/files/publications/MYE19_SOA_WARD.xlsx", "https://www.nisra.gov.uk/publications/2019-mid-year-population-estimates-northern-ireland",
    "pop_ccg", "population", "Clinical commissioning group population estimates: mid-2019", "https://www.ons.gov.uk/file?uri=/peoplepopulationandcommunity/populationandmigration/populationestimates/datasets/clinicalcommissioninggroupmidyearpopulationestimates/mid2019sape22dt6a/sape22dt6amid2019ccg2020estimatesunformatted.zip", "https://www.ons.gov.uk/peoplepopulationandcommunity/populationandmigration/populationestimates/datasets/clinicalcommissioninggroupmidyearpopulationestimates",
    "pop_lad", "population", "Local Authority District population-estimates: mid-2019", "https://www.ons.gov.uk/file?uri=/peoplepopulationandcommunity/populationandmigration/populationestimates/datasets/populationestimatesforukenglandandwalesscotlandandnorthernireland/mid2019april2020localauthoritydistrictcodes/ukmidyearestimates20192020ladcodes.xls", "https://www.ons.gov.uk/peoplepopulationandcommunity/populationandmigration/populationestimates/datasets/populationestimatesforukenglandandwalesscotlandandnorthernireland",
    "pop_counties_ua", "population", "County and Unity Authority (UTLA) population-estimates: mid-2019", "https://www.ons.gov.uk/file?uri=/peoplepopulationandcommunity/populationandmigration/populationestimates/datasets/populationestimatesforukenglandandwalesscotlandandnorthernireland/mid2019april2019localauthoritydistrictcodes/ukmidyearestimates20192019ladcodes.xls", "https://www.ons.gov.uk/peoplepopulationandcommunity/populationandmigration/populationestimates/datasets/populationestimatesforukenglandandwalesscotlandandnorthernireland",
    "pop_trusts_ni", "population", "Health and Social Care Trusts by single year of age and gender: 2020", "https://www.opendatani.gov.uk/dataset/62e7073f-e924-4d3f-81a5-ad45b5127682/resource/f56d85b7-1cf1-4467-8b2e-7a7bce51e637/download/health-and-social-care-trusts-by-single-year-of-age-and-gender-mid-1991-to-mid-2020.csv", "https://data.gov.uk/dataset/62e7073f-e924-4d3f-81a5-ad45b5127682/population-estimates-for-northern-ireland"
  )

usethis::use_data(query_urls, internal = TRUE, overwrite = TRUE)